# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnr < Formula
  desc "A read-only CLI for Linear"
  homepage "https://github.com/StuStirling/lnr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StuStirling/lnr/releases/download/v0.1.0/lnr_0.1.0_darwin_amd64.tar.gz"
      sha256 "38ad63f63d9b58d4b12004447f02b50408bd6d18a49b9959d8232951afdad41f"

      def install
        bin.install "lnr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StuStirling/lnr/releases/download/v0.1.0/lnr_0.1.0_darwin_arm64.tar.gz"
      sha256 "f8a53cec907e530ad27919fd6cacb235b14dfec1893a7ccd356c761dcb5f20ee"

      def install
        bin.install "lnr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuStirling/lnr/releases/download/v0.1.0/lnr_0.1.0_linux_amd64.tar.gz"
      sha256 "f820cef03b0d3eadf3648dfcadfb244670ecc34e3988f869dc81915920ccd906"
      def install
        bin.install "lnr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StuStirling/lnr/releases/download/v0.1.0/lnr_0.1.0_linux_arm64.tar.gz"
      sha256 "93b63c981872c6e46239ca195e92f51d250a511f6310fb7209efbdb5544ebd26"
      def install
        bin.install "lnr"
      end
    end
  end

  test do
    system "#{bin}/lnr", "--version"
  end
end
